# Generated by Django 2.1.4 on 2018-12-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabulation', '0002_auto_20181210_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemarks',
            name='section',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'Both')], default=1),
            preserve_default=False,
        ),
    ]
