# Generated by Django 2.1.4 on 2018-12-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabulation', '0003_attendancemarks_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='contact_number',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
