# Generated by Django 2.1.4 on 2018-12-15 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tabulation', '0004_teacher_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis_type', models.IntegerField(choices=[(1, 'Duration 1 term, evaluation 1 term'), (2, 'Duration 2 terms, evaluation 1 term'), (3, 'duration 2 terms, evaluation 2 terms')], verbose_name='Thesis type')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
            ],
        ),
    ]
