# Generated by Django 3.0.4 on 2020-03-29 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tabulation', '0007_auto_20181218_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabulationStudentWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Student', verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TabulationCourseWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SessionalAssessmentViva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('no_student', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher1', to='tabulation.Teacher')),
                ('teacher2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher2', to='tabulation.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPreparationScriptExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('no_question_t1', models.IntegerField(default=0)),
                ('no_question_t2', models.IntegerField(default=0)),
                ('no_script_t1', models.IntegerField(default=0)),
                ('no_script_t2', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher1', to='tabulation.Teacher')),
                ('teacher2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher2', to='tabulation.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDrawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationCommitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('no_question', models.IntegerField(default=0)),
                ('no_script', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Course', verbose_name='Course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerScriptScrutiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, '1st term'), (2, '2nd term'), (3, 'Special term')])),
                ('year', models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')])),
                ('session', models.CharField(default='', max_length=50)),
                ('no_script', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Discipline', verbose_name='Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabulation.Teacher', verbose_name='Teacher')),
            ],
        ),
    ]
